# Generated by Django 4.1 on 2022-09-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_remove_register_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=1234, max_length=40),
            preserve_default=False,
        ),
    ]
