# Generated by Django 4.1 on 2022-09-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_register_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
