# Generated by Django 4.1 on 2022-09-26 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_avatar'),
        ('UserApp', '0004_delete_register'),
    ]

    operations = [
    ]
