# Generated by Django 4.1 on 2022-09-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_merge_0004_avatar_0004_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(null=True, upload_to='avatares'),
        ),
    ]
